apiVersion: v1
kind: Service
metadata:
  name: laptop-price-api-service
spec:
  type: NodePort
  selector:
    app: laptop-price-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
